version: "3.2"
services:
  web:
    image: wordpress
    restart: always
    links:
      - mysql
    environment:
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DEBUG=true
    ports:
      - 8888:80
    volumes:
      - ./:/var/www/html/wp-content/plugins/git-status
  mysql:
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./mysql:/var/lib/mysql
